# Generated by Django 2.2.3 on 2021-09-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_ba', '0002_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_one',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_three',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_two',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
