# Generated by Django 2.2.3 on 2021-09-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_ba', '0004_auto_20210904_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_three',
        ),
        migrations.AlterField(
            model_name='post',
            name='image_one',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_two',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
