# Generated by Django 2.2.3 on 2021-09-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_ba', '0007_auto_20210905_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_one',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_two',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
